-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bank_accounts
(
    account_id integer NOT NULL DEFAULT nextval('bank_accounts_account_id_seq'::regclass),
    bank_id character varying COLLATE pg_catalog."default" NOT NULL,
    balance numeric(50, 2) NOT NULL,
    CONSTRAINT bank_accounts_pkey PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS public.bank_clients
(
    bank_id character varying COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(200) COLLATE pg_catalog."default" NOT NULL,
    password character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bank_clients_pkey PRIMARY KEY (bank_id),
    CONSTRAINT bank_clients_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.bank_accounts
    ADD CONSTRAINT bank_accounts_bank_id_fkey FOREIGN KEY (bank_id)
    REFERENCES public.bank_clients (bank_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;